<#
.SYNOPSIS
  Resets the local `test_portal_database` to match this directory's SQL files.

.DESCRIPTION
  Runs, in order:
    1. schema.sql    -- DROPS and recreates test_portal_database: all migrated
                        Airtable tables (employees, projects, user_reports, ...)
                        and every junction table.
    2. indexes.sql   -- retrofits idx_user_reports_date for databases that
                        predate it. schema.sql already creates this index on a
                        fresh install, so the "Duplicate key name" error this
                        step produces here is expected -- see indexes.sql's own
                        header comment -- and is reported, not treated as a
                        failure. Any other error still stops the script.
    3. separate.sql  -- portal-native tables schema.sql doesn't own: logs,
                        notifications, calendar events, admin email.
    4. data.sql      -- the migrated Airtable data (generated by
                        migrations/generate_sql_users_projects.py).

  test_portal_database is the real local database the admin app's "portal"
  product connection uses (config/products.php) -- this resets whatever the
  app is currently pointed at, not an isolated scratch copy. Confirms before
  running unless -Force is given.

  Connection details are read from ikaika_admin\.env, following the same
  fallback order config/products.php uses: PORTAL_DB_* first, then DB_*, then
  a hardcoded default -- so this script always targets the same database the
  app would.

.PARAMETER Force
  Skip the confirmation prompt.

.PARAMETER DbHost
.PARAMETER DbPort
.PARAMETER DbUser
.PARAMETER DbPassword
  Override the connection details read from .env.

.PARAMETER MysqlPath
  Path to mysql.exe. Defaults to whatever's on PATH, falling back to the
  standard MySQL Server 8.0 install location.

.EXAMPLE
  .\reset.ps1
  .\reset.ps1 -Force
#>

[CmdletBinding()]
param(
    [string]$DbHost,
    [int]$DbPort,
    [string]$DbUser,
    [string]$DbPassword,
    [string]$MysqlPath,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$scriptDir = $PSScriptRoot
$databaseName = 'test_portal_database'

function Read-EnvValue {
    param([string]$Path, [string]$Key)
    if (-not (Test-Path $Path)) { return $null }
    $line = Get-Content $Path | Where-Object { $_ -match "^\s*$Key\s*=" } | Select-Object -First 1
    if (-not $line) { return $null }
    $value = ($line -split '=', 2)[1]
    return $value.Trim().Trim('"').Trim("'")
}

# Same PORTAL_DB_* -> DB_* -> default fallback config/products.php uses, so this
# script always targets the same database the app's "portal" connection would.
$envFile = Join-Path $scriptDir '..\..\.env'
if (-not $DbHost)     { $DbHost     = Read-EnvValue $envFile 'PORTAL_DB_HOST' }
if (-not $DbHost)     { $DbHost     = Read-EnvValue $envFile 'DB_HOST' }
if (-not $DbHost)     { $DbHost     = '127.0.0.1' }
if (-not $DbPort)     { $DbPort     = Read-EnvValue $envFile 'PORTAL_DB_PORT' }
if (-not $DbPort)     { $DbPort     = Read-EnvValue $envFile 'DB_PORT' }
if (-not $DbPort)     { $DbPort     = 3306 }
if (-not $DbUser)     { $DbUser     = Read-EnvValue $envFile 'PORTAL_DB_USERNAME' }
if (-not $DbUser)     { $DbUser     = Read-EnvValue $envFile 'DB_USERNAME' }
if (-not $DbUser)     { $DbUser     = 'root' }
if (-not $DbPassword) { $DbPassword = Read-EnvValue $envFile 'PORTAL_DB_PASSWORD' }
if (-not $DbPassword) { $DbPassword = Read-EnvValue $envFile 'DB_PASSWORD' }

if (-not $MysqlPath) {
    $found = Get-Command mysql -ErrorAction SilentlyContinue
    if ($found) {
        $MysqlPath = $found.Source
    } else {
        $fallback = 'C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe'
        if (Test-Path $fallback) { $MysqlPath = $fallback }
    }
}
if (-not $MysqlPath -or -not (Test-Path $MysqlPath)) {
    Write-Error "mysql.exe not found. Pass -MysqlPath, or add MySQL's bin directory to PATH."
    exit 1
}

if (-not $Force) {
    Write-Host "This will DROP and recreate '$databaseName' on ${DbHost}:${DbPort} -- the database the admin app's portal connection currently points at." -ForegroundColor Yellow
    $answer = Read-Host "Type 'yes' to continue"
    if ($answer -ne 'yes') {
        Write-Host 'Aborted.'
        exit 1
    }
}

function Invoke-SqlFile {
    param(
        [Parameter(Mandatory)] [string]$Path,
        [Parameter(Mandatory)] [string]$Label,
        [switch]$SelectDatabase,
        [string[]]$IgnorableErrors = @()
    )

    if (-not (Test-Path $Path)) {
        Write-Error "$Label -- file not found: $Path"
        exit 1
    }

    Write-Host "==> $Label" -ForegroundColor Cyan
    $mysqlArgs = @('-h', $DbHost, '-P', $DbPort, '-u', $DbUser, '--default-character-set=utf8mb4')
    if ($SelectDatabase) {
        # schema.sql creates the database itself (DROP + CREATE), so it must NOT be
        # pre-selected -- it may not exist yet. indexes.sql has no USE statement of
        # its own, so it needs this; separate.sql and data.sql already USE it, but
        # passing it here too is harmless.
        $mysqlArgs += @('-D', $databaseName)
    }

    $env:MYSQL_PWD = $DbPassword
    try {
        $output = Get-Content -Raw -Encoding UTF8 -Path $Path | & $MysqlPath @mysqlArgs 2>&1
    } finally {
        Remove-Item Env:\MYSQL_PWD -ErrorAction SilentlyContinue
    }
    $exitCode = $LASTEXITCODE
    $outputText = ($output | Out-String).Trim()

    if ($exitCode -ne 0) {
        $ignorable = $IgnorableErrors | Where-Object { $outputText -match [regex]::Escape($_) }
        if ($ignorable) {
            Write-Host "    expected on a fresh install (schema.sql already created this) -- continuing" -ForegroundColor DarkYellow
            if ($outputText) { Write-Host "    $outputText" -ForegroundColor DarkGray }
            return
        }
        if ($outputText) { Write-Host $outputText -ForegroundColor Red }
        Write-Error "$Label failed (exit $exitCode). Stopping -- nothing after this step ran."
        exit $exitCode
    }

    Write-Host '    done' -ForegroundColor Green
}

Invoke-SqlFile -Path (Join-Path $scriptDir 'schema.sql')   -Label '1/4 schema.sql'
Invoke-SqlFile -Path (Join-Path $scriptDir 'indexes.sql')  -Label '2/4 indexes.sql' -SelectDatabase `
    -IgnorableErrors @("Duplicate key name 'idx_user_reports_date'")
Invoke-SqlFile -Path (Join-Path $scriptDir 'separate.sql') -Label '3/4 separate.sql' -SelectDatabase
Invoke-SqlFile -Path (Join-Path $scriptDir 'data.sql')     -Label '4/4 data.sql' -SelectDatabase

Write-Host "`n$databaseName reset and reloaded." -ForegroundColor Green
